# -*- coding: utf-8 -*-
"""
@author: liutong
Modified for GitHub release: Removed hardcoded Rscript paths, upgraded to 
safe subprocess.run, and improved cross-platform file operations.
"""

import os
import argparse
import subprocess
from pathlib import Path
import pandas as pd


class PeakList:
    """
    A class to manage, process, and export chromatography peak lists.
    """
    
    def __init__(self, peakList=None):
        """
        Initialize the PeakList object.
        """
        if peakList is None:
            self.peakList = pd.DataFrame()
        else:
            self.peakList = peakList

    def from_df(self, df, sampleCols=None):
        """
        Load peak data from a pandas DataFrame and identify sample columns.
        """
        self.peakList = df
        if sampleCols is None:
            # Exclude standard annotation columns to find sample-specific columns
            excluded_cols = {"mz", "rt", "rt_start", "rt_end", "isotope", "adduct", "peak group"}
            self.sampleCols = [col for col in self.peakList.columns if col not in excluded_cols]
        else:
            self.sampleCols = sampleCols

    def to_csv(self, fn):
        """
        Export the current peak list to a CSV file.
        """
        self.peakList.to_csv(fn)

    def to_skyline(self, fn, polarity, moleculeListName="XCMS peaks"):
        """
        Export the peak list to a format compatible with Skyline transition lists.
        """
        transition_list = self.peakList.copy()
        
        # Generate Skyline specific columns
        transition_list["Precursor Name"] = ["unknown " + str(index) for index in transition_list.index]
        transition_list["Explicit Retention Time"] = transition_list["rt"].tolist()
        
        pol_mapper = {"Positive": 1, "Negative": -1}
        transition_list["Precursor Charge"] = [pol_mapper.get(polarity, 1) for _ in range(len(transition_list))]
        transition_list["Precursor m/z"] = transition_list["mz"].tolist()
        transition_list["Molecule List Name"] = moleculeListName
        
        # Reorder and filter columns for Skyline
        columns_to_export = [
            "Molecule List Name", "Precursor Name", "Precursor m/z", 
            "Precursor Charge", "Explicit Retention Time"
        ]
        transition_list = transition_list[columns_to_export]
        transition_list.to_csv(fn, index=False)

    def readXCMSPeakList(self, filename, key=".mzML"):
        """
        Read and parse the peak list generated by the XCMS R script.
        """
        data = pd.read_csv(filename, index_col=0, sep="\t")
        data_dict = {}
        
        # Identify columns that belong to samples based on the given key
        self.sampleCols = [col for col in data.columns if key in col]
        
        for col in self.sampleCols:
            data[col] = data[col].fillna(0)
            
        # Reformat data into a dictionary for fast DataFrame reconstruction
        for index, row in data.iterrows():
            data_dict[index] = {
                "mz": row["mzmed"], 
                "rt": row["rtmed"] / 60, 
                "rt_start": row["rtmin"] / 60,
                "rt_end": row["rtmax"] / 60
            }
            # Append sample intensity values
            for col in self.sampleCols:
                data_dict[index][col] = row[col]

        self.peakList = pd.DataFrame.from_dict(data_dict, orient="index")

    def runXCMS(self, path, fn, polarity, ppm, minWidth, maxWidth, noise=1000, s2n=1, prefilter=2, mzDiff=0.0001, minFrac=0.5):
        """
        Execute the external R script (find_peaks.R) to perform XCMS peak detection.
        """
        script_dir = os.path.dirname(os.path.abspath(__file__))
        r_script_path = os.path.join(script_dir, "find_peaks.R")
        
        r_executable = "/share/software/apps/anaconda3_v2205/envs/stable_R4.2/bin/Rscript"
        
        cmd = [
            r_executable, r_script_path, 
            str(path), str(polarity), str(ppm), 
            str(minWidth), str(maxWidth), str(fn), 
            str(noise), str(s2n), str(prefilter), 
            str(mzDiff), str(minFrac)
        ]
        
        print(f"[*] Executing XCMS R script...")
        try:
            subprocess.run(cmd, check=True)
        except subprocess.CalledProcessError as e:
            print(f"[Error] XCMS script failed to execute. Ensure 'Rscript' is in PATH and XCMS is installed.")
            raise e
        
        # Load the newly generated XCMS peak list
        self.readXCMSPeakList(os.path.join(path, fn))


def get_features(datadir, polarity, ms1ppm, minWidth, maxWidth, s2n=5, noise=100, mzDiff=0.015, prefilter=3):
    """
    Main pipeline function to extract features from MS data using XCMS.
    """
    xcms_temp_file = "xcms_peak_list.csv"
    det = PeakList()
    
    # 1. Run XCMS algorithm via external R script
    det.runXCMS(
        path=datadir, 
        fn=xcms_temp_file, 
        polarity=polarity, 
        ppm=ms1ppm, 
        minWidth=minWidth, 
        maxWidth=maxWidth,
        s2n=s2n, 
        noise=noise, 
        mzDiff=mzDiff, 
        prefilter=prefilter
    )

    # 2. Read and format the initial XCMS output
    det.readXCMSPeakList(os.path.join(datadir, xcms_temp_file))
    peak_list = pd.DataFrame(det.peakList)

    # 3. Clean up and rename columns (keep only mz and rt)
    peak_list = peak_list.iloc[:, :2].reset_index(drop=True)
    peak_list.rename(columns={"rt": "RT"}, inplace=True)

    # 4. Insert 'Compound Name' as the first column
    peak_list['Compound Name'] = ['M' + str(i) for i in range(1, len(peak_list) + 1)]
    peak_list.insert(0, 'Compound Name', peak_list.pop('Compound Name'))

    # 5. Save the formatted peak list and remove the temporary XCMS file
    temp_peak_path = os.path.join(datadir, "peak_list.csv")
    peak_list.to_csv(temp_peak_path, index=False)
    
    # 安全删除临时文件
    temp_xcms_file_path = os.path.join(datadir, xcms_temp_file)
    if os.path.exists(temp_xcms_file_path):
        os.remove(temp_xcms_file_path)

    # 6. Move the finalized peak list to the parent directory
    parent_dir = Path(datadir).parent
    final_peak_path = os.path.join(parent_dir, "peak_list.csv")
    
    # 【核心修复3】：使用 os.replace 代替 os.rename
    # 如果目标文件已存在，os.rename 在 Windows 环境下会直接报错，而 os.replace 具备跨平台覆盖的安全性
    os.replace(temp_peak_path, final_peak_path)

    # =========================
    # Generate ALL_ions dataframe
    # =========================
    all_ions = pd.DataFrame({
        "RT (min)": peak_list["RT"],   # Converted to minutes previously in readXCMSPeakList
        "mw ID": peak_list["Compound Name"]
    })

    # Save the all ions reference file
    all_ions_path = os.path.join(parent_dir, "ALL_ions.xlsx")
    all_ions.to_excel(all_ions_path, index=False)

    return peak_list


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='MetSynQ - Feature Extraction Tool')
    
    parser.add_argument('--ppm', default=10, help='PPM tolerance for ROI extraction')
    # 设为 required=True，防止用户直接运行文件但不传参导致的报错
    parser.add_argument('--mzml', required=True, help='Path to the raw data directory')
    parser.add_argument('--polarity', default='negative', choices=["positive", "negative"],
                        help='Ionization polarity (CentWave parameter)')
    parser.add_argument('--minWidth', default=5, help='Minimum peak width (CentWave parameter)')
    parser.add_argument('--maxWidth', default=50, help='Maximum peak width (CentWave parameter)')
    parser.add_argument('--s2n', default=5, help='Signal-to-noise ratio threshold')
    parser.add_argument('--noise', default=100, help='Noise level threshold')
    parser.add_argument('--mzDiff', default=0.005, help='m/z difference for peak grouping')
    parser.add_argument('--prefilter', default=3, help='Pre-filtering intensity threshold')

    args = parser.parse_args()
    
    # Execute the feature extraction pipeline
    feature = get_features(
        datadir=args.mzml, 
        polarity=args.polarity, 
        ms1ppm=args.ppm, 
        minWidth=args.minWidth, 
        maxWidth=args.maxWidth,
        s2n=args.s2n, 
        noise=args.noise, 
        mzDiff=args.mzDiff, 
        prefilter=args.prefilter
    )